
/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

-- 如果存在这个数据库那么就删除这个数据库
/*Table structure for table `user_mess` */

DROP TABLE IF EXISTS `user_message`;

CREATE TABLE `user_message` (
	`USERNAME` varchar(50) NOT NULL COMMENT '用户姓名',
	`PASSWORD` varchar(6) NOT NULL COMMENT '用户密码',
	`ID` int(10) NOT NULL COMMENT '用户学号',
	`E_MAIL` varchar(50) NOT NULL COMMENT '邮箱地址',
	`SEX` char(1) DEFAULT NULL COMMENT '用户性别',
	`PHONE_NUMBER` int(11) NOT NULL COMMENT '用户手机号',
	`MAJOR` varchar(50) NOT NULL COMMENT '用户专业',
	`CLASS_NUMBER` int(8) DEFAULT NULL COMMENT '用户班级代号',
	`STUDY_DIRECTION` varchar(50) DEFAULT NULL COMMENT '用户学习方向',
	`AGE` int(3) DEFAULT NULL COMMENT '用户年龄',
	`BIRTH` date DEFAULT NULL COMMENT '用户出生日期',
	`HABIT` varchar(50) DEFAULT NULL COMMENT '用户爱好',
	`STATE` int(1) NOT NULL DEFAULT '0' COMMENT '用户目前功能状态',
	 UNIQUE (`ID`),
	 UNIQUE (`E_MAIL`),
	 UNIQUE (`USERNAME`),
	 UNIQUE (`PHONE_NUMBER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `user_mess` */

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
